export default {
  startingTiles: [
    "v",
    "L"
  ],
  fontSizes: [64, 48, 32, 24, 18],
  appearance: {
    color: {
      v: "#eee4da",
      L: "#ead3a8",
      t: "#f3b27a",
      m: "#f68d56",
      V: "#f65e3b",
      qZar: "#ff3b0e",
      p: "#edcf72",
      g: "#eac752",
      F: "#dbb435",
      A: "#d2a81b",
      P: "#b28a00",
      R: "#3e3933",
      U: "#191715",
      I: "#212044",
      q: "#393977",
    },
    fontColor: {
      v: "black",
      L: "black",
    },
    display: {
      "v": ["υ", "м/с", "img speedometer"],
      "L": ["L", "м.", "img ruler"],
      "t": ["t", "сек.", "img clock"],
      "m": ["m", "кг", "img scale"],
      "V": ["V", "м³", "img cube"],
      "qZar": ["ρ", "кг/м³", "img plotnost"],
      "p": ["p", "Па.", "img press"],
      "g": ["g", "м/с²", "img uskorenie"],
      "F": ["F", "Н.", "img dynamometer"],
      "A": ["A", "Дж.", "img work"],
      "P": ["P", "Ватт.", "img motor"],
      "R": ["R", "Ом.", "img resistance"],
      "U": ["U", "В.", "img voltmeter"],
      "I": ["I", "А.", "img amperemeter"],
      "q": ["q", "Кл."],
      "n": ["η", "%"]
    }
  },
  combinations: {
    "v v": "L",
    "L L": "t",
    "t t": "m",
    "m m": "V",
    "V V": "qZar",
    "qZar qZar": "p",
    "p p": "g",
    "g g": "F",
    "F F": "A",
    "A A": "P",
    "P P": "R",
    "R R": "U",
    "U U": "I",
    "I I": "q",
    "q q": "n"
  },
};
