export default {
  startingTiles: [
    /* "ν",
    "S",
    "l",
    "m",
    "g",
    "t",
    "t°",
    "g",
    "π",
    "2",
    "ρ",
    "λ",
    "V",
    "v", */
    "m",
  ],
  fontSizes: [64, 48, 32],
  appearance: {
    color: {
      /* l: "#7940E7",
      t: "#5EBA6C",
      v: "#FCD61F",
      m: "#787593",
      g: "#3CBC7B",
      F: "#738079",
      E: "#A0D924",
      cm: "#DA9B1F",
      "t°": "#32DF11",
      S: "#86863F",
      Pᶢ: "#093A91",
      ρ: "#886E4E",
      ρg: "#595716",
      gl: "#EAAA91",
      V: "#EBC025",
      L: "#9DEDFF",
      λ: "#BAD48A",
      p: "#F0F611",
      q: "#282877",
      I: "#278476",
      "I²": "#57F5E4",
      R: "#ACF7BE",
      "I²R": "#ED2E3A",
      Rt: "#DE4DC0",
      IV: "#1550FE",
      Vt: "#84EC9B",
      "v²": "#01C6A8",
      "v²/R": "#DAFC17",
      "r²": "#8BAFB3",
      π: "#FFB514",
      "2": "#F50115",
      "2π": "#22988C",
      πr: "#1099D8",
      k: "#489916",
      gV: "#BC2239",
      υ: "#D838E6",
      P: "#545F34",
      A: "#2CD156",
      U: "#4E6FB8",
      Q: "#99AF62" */
      m: "#eee4da",
      V: "#eee1c9",
      P: "#f3b27a",
      S: "#f69664",
      F: "#f67c5f",
      E: "#f65e3b",
      A: "#edcf72",
      U: "#edcc61",
      I: "#edc850",
      R: "#edc53f",
      T: "#edc22e",
      Q: "#3e3933",
      l: "#191715",
      t: "#212044",
      υ: "#393977",
    },
    fontColor: {
      /* p: "black",
      A: "black",
      R: "black",
      Q: "black" */
      m: "black",
      V: "black",
    },
  },
  combinations: {
    /* "l t": "v",
    "m g": "F",
    "F l": "E",
    "cm t°": "E",
    "F S": "Pᶢ",
    "ρ g": "ρg",
    "g l": "gl",
    "ρg l": "Pᶢ",
    "ρ gl": "Pᶢ",
    "m ρ": "V",
    "m L": "E",
    "m λ": "E",
    "m v": "p",
    "l l": "S",
    "S l": "V",
    "q t": "I",
    "V R": "I",
    "m M": "ν",
    "I I": "I²",
    "I² R": "I²R",
    "R t": "Rt",
    "I²R t": "E",
    "I² Rt": "E",
    "I V": "IV",
    "V t": "Vt",
    "IV t": "E",
    "I Vt": "E",
    "v v": "v²",
    "v² R": "v²/R",
    "v²/R t": "E",
    "v² Rt": "E",
    "r r": "r²",
    "π r²": "S",
    "2 π": "2π",
    "π r": "πr",
    "2π r": "l",
    "2 πr": "l",
    "g V": "gV",
    "ρg V": "F",
    "ρ gV": "F",
    "k l": "F",
    "l v": "t",
    "t v": "l",
    "m F": "g",
    "g F": "m",
    "F E": "l",
    "l E": "F",
    "cm E": "t°",
    "t° E": "cm",
    "F Pᶢ": "S",
    "S Pᶢ": "F",
    "ρ ρg": "g",
    "g ρg": "ρ",
    "g gl": "l",
    "l gl": "g",
    "ρg Pᶢ": "l",
    "l Pᶢ": "ρg",
    "ρ Pᶢ": "gl",
    "gl Pᶢ": "ρ",
    "m V": "ρ",
    "ρ V": "m",
    "m E": "λ",
    "L E": "m",
    "λ E": "m",
    "m p": "v",
    "v p": "m",
    "l S": "l",
    "S V": "l",
    "l V": "S",
    "q I": "t",
    "t I": "q",
    "V I": "R",
    "R I": "V",
    "m ν": "M",
    "M ν": "m",
    "I I²": "I",
    "I² I²R": "R",
    "R I²R": "I²",
    "R Rt": "t",
    "t Rt": "R",
    "I²R E": "t",
    "t E": "v²/R",
    "I² E": "Rt",
    "Rt E": "v²",
    "I IV": "V",
    "V IV": "I",
    "V Vt": "t",
    "t Vt": "V",
    "IV E": "t",
    "I E": "Vt",
    "Vt E": "I",
    "v v²": "v",
    "v² v²/R": "R",
    "R v²/R": "v²",
    "v²/R E": "t",
    "v² E": "Rt",
    "r r²": "r",
    "π S": "r²",
    "r² S": "π",
    "2 2π": "π",
    "π 2π": "2",
    "π πr": "r",
    "r πr": "π",
    "2π l": "r",
    "r l": "2π",
    "2 l": "πr",
    "πr l": "2",
    "g gV": "V",
    "V gV": "g",
    "ρg F": "V",
    "V F": "ρg",
    "ρ F": "gV",
    "gV F": "ρ",
    "k F": "l",
    "l F": "k" */
    "m m": "V",
    "V V": "P",
    "P P": "S",
    "S S": "F",
    "F F": "E",
    "E E": "A",
    "A A": "U",
    "U U": "I",
    "I I": "R",
    "R R": "T",
    "T T": "Q",
    "Q Q": "l",
    "l l": "t",
    "t t": "υ",
  },
};
